<?xml version="1.0" encoding="utf-8"?>
<ns1:log count="2" start="0" total="2" xmlns:ns1="http://ns.dataone.org/service/types/v2.0">
  <logEntry>
    <entryId>[volatile]</entryId>
    <identifier>PID_pwhwsulxembq</identifier>
    <ipAddress>127.0.0.1</ipAddress>
    <userAgent>DataONE_Python/2.3.5 +http://dataone.org/</userAgent>
    <subject>disabled_auth_subj</subject>
    <event>create</event>
    <dateLogged>2006-07-23T02:01:31</dateLogged>
    <nodeIdentifier>urn:node:MyMemberNode</nodeIdentifier>
  </logEntry>
  <logEntry>
    <entryId>[volatile]</entryId>
    <identifier>PID_pwhwsulxembq</identifier>
    <ipAddress>127.0.0.1</ipAddress>
    <userAgent>DataONE_Python/2.3.5 +http://dataone.org/</userAgent>
    <subject>disabled_auth_subj</subject>
    <event>update</event>
    <dateLogged>1997-01-17T12:49:20</dateLogged>
    <nodeIdentifier>urn:node:MyMemberNode</nodeIdentifier>
  </logEntry>
</ns1:log>
